name: CI/CD

on:
  push:
    branches:
      - desenvolvimento
      - producao

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Define as configurações de acordo com a branch
      - name: Definir ambiente
        id: ambiente
        # se a branch for 'desenvolvimento', o deploy é no ambiente de homologação
        # senão
        run: |
          if [ "${GITHUB_REF_NAME}" = "desenvolvimento" ]; then
            echo "ambiente=hom" >> "$GITHUB_OUTPUT"
            echo "base=/estudos/ci-cd/hom/lista-tarefas/" >> "$GITHUB_OUTPUT"
            
          elif [ "${GITHUB_REF_NAME}" = "producao" ]; then
            echo "ambiente=prd" >> "$GITHUB_OUTPUT"
            echo "base=/estudos/ci-cd/prd/lista-tarefas/" >> "$GITHUB_OUTPUT"
          fi

      # Baixa o código da branch
      - name: Baixar código
        uses: actions/checkout@v4

      # Configura o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Instala as dependências
      - name: Instalar dependências
        run: npm ci

      # Gera o build do Vue/Vite
      - name: Gerar build
        env:
          VITE_BASE: ${{ steps.ambiente.outputs.base }}
        run: npm run build

      # Configura a chave SSH
      - name: Configurar SSH
        env:
          SSH_KEY: ${{ secrets.CHAVE_SSH_VPS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ vars.IP_VPS }} >> ~/.ssh/known_hosts

      # Cria backup
      - name: Criar backup
        run: |
          ssh -i ~/.ssh/github_actions \
            ${{ vars.USUARIO_VPS }}@${{ vars.IP_VPS }} \
            "mkdir -p /var/www/html/estudos/ci-cd/backups"

          ssh -i ~/.ssh/github_actions \
            ${{ vars.USUARIO_VPS }}@${{ vars.IP_VPS }} \
            "tar -czf /var/www/html/estudos/ci-cd/backups/lista-tarefas-\$(date +%Y%m%d-%H%M%S).tar.gz -C /var/www/html/estudos/ci-cd/${{ steps.ambiente.outputs.ambiente }} lista-tarefas"

      # Copia o build para o ambiente
      - name: Deploy
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/github_actions" \
            --exclude="config.js" \
            ./dist/ \
            ${{ vars.USUARIO_VPS }}@${{ vars.IP_VPS }}:/var/www/html/estudos/ci-cd/${{ steps.ambiente.outputs.ambiente }}/lista-tarefas/